config/routes.rb
Rails.application.routes.draw do
  resources :senders
  resources :countries
  resources :r_moneys
  resources :s_moneys

  root 'senders#new'
 # get 'send_money/New_Sender_Conf' => 'senders#new_sender_conf'
  get 'send_money/Sender_Index' => 'senders#index'
  get 'send_money/Show_Transaction' => 'senders#show'
  get 'r_money/search' => 'r_moneys#search_pickups'
  get 'r_money/payout' => 'r_moneys#payout'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/country.rb
class Country < ApplicationRecord
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name, :mim_tier1_cost, :mim_tier1_limit, :mim_tier2_cost,
        :mim_tier2_limit, :mim_tier3_cost, :mim_tier3_limit, :mim_tier4_cost, :mim_tier4_limit,
        :nextday_tier1_cost, :nextday_tier1_limit, :nextday_tier2_cost, :nextday_tier2_limit,
        :nextday_tier3_cost, :nextday_tier3_limit, :nextday_tier4_cost, :nextday_tier4_limit, 
        :exchange_rate, :require_id, :require_testq, :communist_q, :req_twoid)
    end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_form.html.erb
<%= simple_form_for(@country) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    
    <%= f.input :mim_tier1_cost %>
    <%= f.input :mim_tier1_limit %>
    <%= f.input :mim_tier2_cost %>
    <%= f.input :mim_tier2_limit %>
    <%= f.input :mim_tier3_cost %>
    <%= f.input :mim_tier3_limit %>
    <%= f.input :mim_tier4_cost %>
    <%= f.input :mim_tier4_limit %>
    
    <%= f.input :nextday_tier1_cost %>
    <%= f.input :nextday_tier1_limit %>
    <%= f.input :nextday_tier2_cost %>
    <%= f.input :nextday_tier2_limit %>
    <%= f.input :nextday_tier3_cost %>
    <%= f.input :nextday_tier3_limit %>
    <%= f.input :nextday_tier4_cost %>
    <%= f.input :nextday_tier4_limit %>


    <%= f.input :exchange_rate %>
    <%= f.input :require_id %>
    <%= f.input :require_testq %>
    <%= f.input :communist_q %>
    <%= f.input :req_twoid %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Countries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mim t1 cost</th>
      <th>Mim t1 limit</th>
      <th>Mim t2 cost</th>
      <th>Mim t2 limit</th>
      <th>Mim t3 cost</th>
      <th>Mim t3 limit</th>
      <th>Mim t4 cost</th>
      <th>Mim t4 limit</th>
      <th>Nextday t1 cost</th>
      <th>Nextday t1 limit</th>
      <th>Nextday t2 cost</th>
      <th>Nextday t2 limit</th>
      <th>Nextday t3 cost</th>
      <th>Nextday t3 limit</th>
      <th>Nextday t4 cost</th>
      <th>Nextday t4 limit</th>
      <th>Exchange rate</th>
      <th>Require</th>
      <th>Require testq</th>
      <th>Communist q</th>
      <th>Req twoid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= country.name %></td>
        <td><%= country.mim_tier1_cost %></td>
        <td><%= country.mim_tier1_limit %></td>
        <td><%= country.mim_tier2_cost %></td>
        <td><%= country.mim_tier2_limit %></td>
        <td><%= country.mim_tier3_cost %></td>
        <td><%= country.mim_tier3_limit %></td>
        <td><%= country.mim_tier4_cost %></td>
        <td><%= country.mim_tier4_limit %></td>
        <td><%= country.nextday_tier1_cost %></td>
        <td><%= country.nextday_tier1_limit %></td>
        <td><%= country.nextday_tier2_cost %></td>
        <td><%= country.nextday_tier2_limit %></td>
        <td><%= country.nextday_tier3_cost %></td>
        <td><%= country.nextday_tier3_limit %></td>
        <td><%= country.nextday_tier4_cost %></td>
        <td><%= country.nextday_tier4_limit %></td>
        <td><%= country.exchange_rate %></td>
        <td><%= country.require_id %></td>
        <td><%= country.require_testq %></td>
        <td><%= country.communist_q %></td>
        <td><%= country.req_twoid %></td>
        <td><%= link_to 'Show', country %></td>
        <td><%= link_to 'Edit', edit_country_path(country) %></td>
        <td><%= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Country', new_country_path %>

app/views/countries/new.html.erb
<h1>New Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @country.name %>
</p>


<p>
  <strong>Mim t1 cost:</strong>
  <%= @country.mim_tier1_cost %>
</p>

<p>
  <strong>Mim t1 limit:</strong>
  <%= @country.mim_tier1_limit %>
</p>

<p>
  <strong>Mim t2 cost:</strong>
  <%= @country.mim_tier2_cost %>
</p>

<p>
  <strong>Mim t2 limit:</strong>
  <%= @country.mim_tier1_limit %>
</p>

<p>
  <strong>Mim t3 cost:</strong>
  <%= @country.mim_tier3_cost %>
</p>

<p>
  <strong>Mim t3 limit:</strong>
  <%= @country.mim_tier1_limit %>
</p>

<p>
  <strong>Mim t4 cost:</strong>
  <%= @country.mim_tier4_cost %>
</p>

<p>
  <strong>Mim t4 limit:</strong>
  <%= @country.mim_tier4_limit %>
</p>

<br>

<p>
  <strong>Nextday tier 1 cost:</strong>
  <%= @country.nextday_tier1_cost %>
</p>

<p>
  <strong>Nextday tier 1 limit:</strong>
  <%= @country.nextday_tier1_limit %>
</p>

<p>
  <strong>Nextday tier 2 cost:</strong>
  <%= @country.nextday_tier2_cost %>
</p>

<p>
  <strong>Nextday tier 2 limit:</strong>
  <%= @country.nextday_tier2_limit %>
</p>

<p>
  <strong>Nextday tier 3 cost:</strong>
  <%= @country.nextday_tier3_cost %>
</p>

<p>
  <strong>Nextday tier 3 limit:</strong>
  <%= @country.nextday_tier3_limit %>
</p>

<p>
  <strong>Nextday tier 4 cost:</strong>
  <%= @country.nextday_tier4_cost %>
</p>

<p>
  <strong>Nextday tier 4 limit:</strong>
  <%= @country.nextday_tier4_limit %>
</p>

<br>

<p>
  <strong>Exchange rate:</strong>
  <%= @country.exchange_rate %>
</p>

<p>
  <strong>Require ID:</strong>
  <%= @country.require_id %>
</p>

<p>
  <strong>Require testq:</strong>
  <%= @country.require_testq %>
</p>

<p>
  <strong>Communist q:</strong>
  <%= @country.communist_q %>
</p>

<p>
  <strong>Req twoid:</strong>
  <%= @country.req_twoid %>
</p>

<%= link_to 'Edit', edit_country_path(@country) %> |
<%= link_to 'Back', countries_path %>