config/routes.rb
Rails.application.routes.draw do
  resources :senders
  resources :countries
  resources :r_moneys
  resources :s_moneys

  root 'senders#new'
 # get 'send_money/New_Sender_Conf' => 'senders#new_sender_conf'
  get 'send_money/Sender_Index' => 'senders#index'
  get 'send_money/Show_Transaction' => 'senders#show'
  get 'r_money/search' => 'r_moneys#search_pickups'
  get 'r_money/payout' => 'r_moneys#payout'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/s_money.rb
class SMoney < ApplicationRecord
end

app/controllers/s_moneys_controller.rb
class SMoneysController < ApplicationController
	before_action :set_smoney, only: [:new_sender_conf, :show_transaction]

	def sender_index
		@senders = Sender.all
	end

	def new_sender
		@sender = Sender.new
		@countries = Country.all
	end

	def new_sender_conf
	end

	def show_transaction
	end

	def create
		@sender = Sender.new(sender_params)

	    respond_to do |format|
	      if @sender.save
	        format.html { redirect_to @sender, notice: 'Transaction was successfully created.' }
	        format.json { render :show, status: :created, location: @sender }
	      else
	        format.html { render :new }
	        format.json { render json: @sender.errors, status: :unprocessable_entity }
	      end
    end

	end

	private
	def set_smoney
      @sender = Sender.find(params[:id])
    end

	def sender_params
		params.require(:sender).permit(:f_name, :m_name, :l_name, :pat_name, :mat_name, :phone_number, :email, :address, :address_zip, :address_state, :recipients, :id_type, :lic_number, :pass_number, :gov_number, :id_dob, :lic_state, :pass_country, :gov_country )
	end



end

app/helpers/s_moneys_helper.rb
module SMoneysHelper
end

app/views/s_moneys/_form.html.erb
<%= simple_form_for @sender do |f| %> 

	<%= f.input :f_name %>
	<%= f.input :m_name %>
	
	<%= f.input :familyname, as: :boolean, checked_value: true, unchecked_value: false %>
	
	<%= f.input :l_name %>
	<%= f.input :pat_name %>
	<%= f.input :mat_name %>
	<%= f.input :address %>
	<%= f.input :address_zip %>
	<%= f.input :address_state %>
	<%= f.input :phone_number %>
	
	<br>
	
	<%= f.input :email  %>
	
	<br>
	
	<%= f.input :id_type %>
	<%= f.input :lic_number %>
	<%= f.input :pass_number %>
	<%= f.input :gov_number  %>
	<%= f.input :id_dob  %>
	<%= f.input :lic_state  %>
	<%= f.input :pass_country %>
	<%= f.input :gov_country %>

	<br>

	<%= f.submit 'Submit Transaction' %>

<% end %>

app/views/s_moneys/new_sender.html.erb
<h1>Welcome to the send page!</h1>

<%= render 'form', s_money: @sender %>

<%= link_to "Sender Index", send_money_send_index_path %>

app/views/s_moneys/new_sender_conf.html.erb
New_Sender_Conf.html.erb

app/views/s_moneys/sender_index.html.erb
<p>nothin's here yet</p>

app/views/s_moneys/show_transaction.html.erb
Show_Transaction.html.erb