config/routes.rb
Rails.application.routes.draw do
  resources :senders
  resources :countries
  resources :r_moneys
  resources :s_moneys

  root 'senders#new'
 # get 'send_money/New_Sender_Conf' => 'senders#new_sender_conf'
  get 'send_money/Sender_Index' => 'senders#index'
  get 'send_money/Show_Transaction' => 'senders#show'
  get 'r_money/search' => 'r_moneys#search_pickups'
  get 'r_money/payout' => 'r_moneys#payout'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sender.rb
class Sender < ApplicationRecord
end

app/controllers/senders_controller.rb
class SendersController < ApplicationController
  before_action :set_sender, only: [:show, :edit, :update, :destroy]

  # GET /senders
  # GET /senders.json
  def index
    @senders = Sender.all
  end

  # GET /senders/1
  # GET /senders/1.json
  def show
    @trans = Transaction.all
  end

  # GET /senders/new
  def new
    @countries = Country.all
    @sender = Sender.new
    @trans = Transaction.new
  end

  # GET /senders/1/edit
  def edit
  end

  # POST /senders
  # POST /senders.json
  def create
    @sender = Sender.new(sender_params)

    num0 = rand(0...10).to_s
    num1 = rand(0...10).to_s
    num2 = rand(0...10).to_s
    num3 = rand(0...10).to_s
    num4 = rand(0...10).to_s
    num5 = rand(0...10).to_s
    num6 = rand(0...10).to_s
    num7 = rand(0...10).to_s
    num8 = rand(0...10).to_s
    num9 = rand(0...10).to_s

    if @sender.create_account == true
      @cus_num = num0 + num1 + num2 + num3 + num4 + num5

    else
      @cus_num = nil
    end

    @mtcn_num = num0 + num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num9

    @sender.customer_number = @cus_num
    @sender.mtcn = @mtcn_num

    @trans = Transaction.new
    @trans.mtcn = @sender.mtcn
    @trans.sender_f_name = @sender.f_name
    @trans.sender_m_name = @sender.m_name
    @trans.sender_l_name = @sender.l_name + @sender.pat_name + @sender.mat_name
    @trans.expected_f_name = @sender.reciever_f_name
    @trans.expected_m_name = @sender.reciever_m_name
    @trans.expected_l_name = @sender.reciever_l_name + @sender.reciever_pat_name + @sender.reciever_mat_name
    @trans.test_quest_answer = @sender.test_answer
    @trans.test_question = @sender.test_question
    @trans.payout_amount = @sender.conversion_amount

    respond_to do |format|
      if @sender.save && @trans.save
        format.html { redirect_to @sender, notice: 'Sender was successfully created.' }
        format.json { render :show, status: :created, location: @sender }
      else
        format.html { render :new }
        format.json { render json: @sender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /senders/1
  # PATCH/PUT /senders/1.json
  def update
    respond_to do |format|
      if @sender.update(sender_params)
        format.html { redirect_to @sender, notice: 'Sender was successfully updated.' }
        format.json { render :show, status: :ok, location: @sender }
      else
        format.html { render :edit }
        format.json { render json: @sender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /senders/1
  # DELETE /senders/1.json
  def destroy
    @sender.destroy
    respond_to do |format|
      format.html { redirect_to senders_url, notice: 'Sender was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sender
      @sender = Sender.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sender_params
      params.require(:sender).permit(:f_name, :m_name, :l_name, :pat_name, :mat_name, 
        :phone_number, :create_account, :email, :address, :address_zip, :address_state, :recipients, :id_type, 
        :lic_number, :pass_number, :gov_number, :id_dob, :lic_state, :pass_nation, :gov_nation, 
        :send_amount, :final_amount, :sendforself, :payout_nation, :payout_state, :reciever_f_name, 
        :reciever_m_name, :reciever_l_name, :reciever_pat_name, :reciever_mat_name,:test_answer, :test_question, :test_answer,
        :customer_number, :mtcn, :send_date, :payout_date, :conversion_amount)
    end

    def trans_params
      params.require(:transaction).permit(:mtcn, :sender_f_name, :sender_m_name, :sender_l_name, 
        :reciever_f_name, :reciever_m_name, :reciever_l_name, :rec_address, :rec_phone, 
        :rec_zip, :rec_state, :rec_id_type, :rec_pass_num, :rec_pass_dob, :rec_pas_country, 
        :rec_lic_num, :rec_lic_state, :rec_lic_dob, :rec_govid_num, :rec_govid_country, 
        :rec_govid_dob, :reciever_city, :test_quest_answer, :second_id, :second_id_type, 
        :idtwo_pass_country, :idtwo_pass_num, :idtwo_pass_dob, :idtwo_lic_state, 
        :idtwo_lic_dob_, :idtwo_lic_num, :idtwo_gov_country, :idtwo_gov_num, 
        :idtwo_gov_dob, :trans_paid, :test_quest_answer, :payout_amount)
    end


end

app/helpers/senders_helper.rb
module SendersHelper
end

app/views/senders/_form.html.erb
<%= simple_form_for @sender do |f| %> 

    <div class='container'>
    	<div class="card">
    		<div class="container">
			    <div id="paternal_check" >
			        <label class="form-check-label"> Do you wish to use family name setting?
			            <button type="button" class="btn btn-secondary btn-sm">Yes</button>
			        </label>    
			    </div>

		    	<div id="paternal_uncheck" >
		        	<label class="form-check-label"> Do you wish to use family name setting?
		            	<button type="button" class="btn btn-secondary btn-sm">No</button>
		        	</label>
		    	</div>  

			    <%= f.input :f_name, label: "First Name:  " %> 
			    <%= f.input :m_name, label: "Middle Name:  " %>
			            
			    <div id='last_name'>
			      <%= f.input :l_name, label: "Last Name: " %>
			    </div>
			    
			    <div id="paternal_name">
				    <p>
				        <span>
				        	<%= f.input :pat_name, label: "Paternal Name: " %> 
				         	<%= f.input :mat_name, label: "Maternal Name: " %>
				        </span>
				    </p>
			    </div>
			</div>
		</div>

	    <br>

	    <div class="card">
	    	<div class="container">
	    		<p><%= f.input :create_account, as: :boolean, checked_value: true, unchecked_value: false, label: "             Assign A Customer number?:" %></p>
			</div>
		</div>

	    <br>
	    <br>

	    <div class="card">
	    	<div class="container">
	    		<p>
	    			<%= f.input :email, label: "E-Mail Address: "  %>
	    		</p>
	    	</div>
	    </div>
	    <br>

	    <br>

	    <div class="card">
	    	<div class="container">
	    
			    <div id="send_country">
			    	<%= f.input :reciever_country, collection: @countries, input_html: { multiple: false}, label: "Send To: "  %>
			    </div>
		

			    <div id='country_input_default'>
			    	<!-- <%= f.input :send_amount, input_html: { :class => "send_amount" }, label: "Send Amount: " %> -->

			    	<p>Send Amount: <input type="text" class="send_amount"></input></p>
			          
			    	<p>
			    		The exchange rate for <span class="reciever_country">this country</span> is: <span class="exchange_rate"> 1 </span>  
			    	</p>
			          
				    <p>
				    	Local Currency payout: 
				        <input type="text" class="conversion_amount"></input>
				    </p>

				    <input type="text" class="final_amount"></input>

			      	<!-- <%= f.input :final_amount, input_html: { :class => "final_amount" }, as: :currency, label: "Total Amount: " %>    -->
			    </div>
		    
			    <% @countries.each do |c| %>
				    <div class='country_input' value="<%= c.name %>">
				    	<!--<%= f.input :send_amount, input_html: { 
				          :class => "send_amount",
				          :name => c.name
				           }, as: :currency, label: "Send Amount: " %> -->

				        <p>Send Amount: <input type="text" name='<%= c.name %>' class="send_amount"></input></p>
				        
				        <p>The exchange rate for <span class="reciever_country"><%= c.name %></span> is: <span class="exchange_rate" name='<%= c.name %>' value='<%= c.exchange_rate %>'> <%= c.exchange_rate %> </span>.</p>
				          
				        <p> Local Currency Payout: 
				            <input type="text" name='<%= c.name %>' class="conversion_amount"></input>

				            <!-- <%= f.input :conversion_amount, input_html: { 
					          :class => "conversion_amount",
					          :name => c.name 
					         }, as: :currency, label: "Conversion Amount: " %> -->


				        </p>

				        <p>Total Amount: <input type="text" name='<%= c.name %>' class="final_amount"></input></p>
				        
				        <!-- <%= f.input :final_amount, input_html: { 
				          :class => "final_amount",
				          :name => c.name 
				         }, as: :currency, label: "Total Amount: " %> -->
				        
				        <br>

				        <div class="send_option" name="<%= c.name %>">
				          
				        	<!-- Money in Minutes Tier 1 -->
				        	<div class="mim_tier1" name="<%= c.name %>" value='<%= c.mim_tier1_limit %>' >
				            	<div class="form-check">
				            		<label class="form-check-label">
				                		<input type="radio" class="form-check-input" name="fee_select" value="<%= c.mim_tier1_cost %>" >
				                    	<span>Cost: $<span class="mim_tier1_amnt" name="<%= c.name %>" value="<%= c.mim_tier1_cost %>" ><%= c.mim_tier1_cost %></span> Money-In-Minutes - Money will be available in 15 to 30 minutes.</span>
				                	</label>
				            	</div>
				        	</div>
				          
					        <!-- Money in Minutes Tier 2 -->
					        <div class="mim_tier2" name="<%= c.name%>" value="<%= c.mim_tier2_limit %>" >
					            <div class="form-check">
					            	<label class="form-check-label">
					                	<input type="radio" class="form-check-input" name="fee_select" value="<%= c.mim_tier2_cost %>" >
					                    <span>Cost: $<span class="mim_tier2_amnt" name="<%= c.name %>" value="<%= c.mim_tier2_cost %>" ><%= c.mim_tier2_cost %> </span>
					                    Money-In-Minutes - Money will be available in 15 to 30 minutes.</span>
					                </label>
					            </div>
					        </div>  
					          
					        <!-- Money in Minutes Tier 3 -->
					        <div class="mim_tier3" name="<%= c.name%>" value="<%= c.mim_tier3_limit %>" >
					            <div class="form-check">
					            	<label class="form-check-label">
					                	<input type="radio" class="form-check-input" name="fee_select" value="<%= c.mim_tier3_cost %>" >
					                    <span>Cost: $<span class="mim_tier3_amnt" name="<%= c.name %>" value="<%= c.mim_tier3_cost %>" ><%= c.mim_tier3_cost %> </span>
					                    Money-In-Minutes - Money will be available in 15 to 30 minutes.</span>
					                </label>
					            </div>
					        </div>
					          
					        <!-- Money in Minutes Tier 4 -->
					        <div class="mim_tier4" name="<%= c.name%>" value="<%= c.mim_tier4_limit %>" >
					            <div class="form-check">
					            	<label class="form-check-label">
					                	<input type="radio" class="form-check-input" name="fee_select" value="<%= c.mim_tier4_cost %>" >
					                    <span>Cost: $<span class="mim_tier4_amnt" name="<%= c.name %>" value="<%= c.mim_tier4_cost %>" ><%= c.mim_tier4_cost %> </span>
					                    Money-In-Minutes - Money will be available in 15 to 30 minutes.</span>
					                </label>
					            </div>
					        </div>

					        <!-- NextDay Tier 1 -->
					        <div class="nextday_tier1" name="<%= c.name%>" value="<%= c.nextday_tier1_limit %>" >
					            <div class="form-check">
					            	<label class="form-check-label">
					            		<input type="radio" class="form-check-input" name="fee_select" value="<%= c.nextday_tier1_cost %>">
					                    <span>Cost: $<span class="nxtday_amnt" name="<%= c.name %>" value="<%= c.nextday_tier1_cost %>"><%= c.nextday_tier1_cost %> </span>
					                    Next-Day Service - Money will be available at the start of the next day.</span>
					                </label>
					            </div>
					        </div>
					          
					        <!-- NextDay Tier 2 -->
					        <div class="nextday_tier2" name="<%= c.name%>" value="<%= c.nextday_tier2_limit %>" >
					            <div class="form-check">
					            	<label class="form-check-label">
					            		<input type="radio" class="form-check-input" name="fee_select" value="<%= c.nextday_tier2_cost %>">
					                    <span>Cost: $<span class="nxtday_amnt" name="<%= c.name %>" value="<%= c.nextday_tier2_cost %>"><%= c.nextday_tier2_cost %> </span>
					                    Next-Day Service - Money will be available at the start of the next day.</span>
					                </label>
					            </div>
					        </div>

					        <!-- NextDay Tier 3 -->
					        <div class="nextday_tier3" name="<%= c.name%>" value="<%= c.nextday_tier3_limit %>" >
					        	<div class="form-check">
					        		<label class="form-check-label">
					        			<input type="radio" class="form-check-input" name="fee_select" value="<%= c.nextday_tier3_cost %>">
					                    <span>Cost: $<span class="nxtday_amnt" name="<%= c.name %>" value="<%= c.nextday_tier3_cost %>"><%= c.nextday_tier3_cost %> </span>
					                    Next-Day Service - Money will be available at the start of the next day.</span>
					                </label>
					            </div>
					        </div>  

					        <!-- NextDay Tier 4 -->
					        <div class="nextday_tier4" name="<%= c.name%>" value="<%= c.nextday_tier4_limit %>" >
					        	<div class="form-check">
					        		<label class="form-check-label">
					        			<input type="radio" class="form-check-input" name="fee_select" value="<%= c.nextday_tier4_cost %>">
					                    <span>Cost: $<span class="nxtday_amnt" name="<%= c.name %>" value="<%= c.nextday_tier4_cost %>"><%= c.nextday_tier4_cost %> </span>
					                    Next-Day Service - Money will be available at the start of the next day.</span>
					                </label>
					            </div>
					        </div>
					    </div>
					</div>
			    

				<% end %>

						    <div id="hide_send_amount">
							    <%= f.input :send_amount, input_html: { 
								          :class => "send_amount",
								          :id => "send_amount_final"
								           }, as: :currency, label: "Send Amount: " %>
							</div>
							
							<div id="hide_conv_amount">
								<%= f.input :conversion_amount, input_html: { 
									          :class => "conversion_amount",
									          :id => "conversion_amount_final"
									         }, as: :currency, label: "Conversion Amount: " %>
							</div>
							
							<div id="hide_final_amount">
								<%= f.input :final_amount, input_html: { 
								          :class => "final_amount",
								          :id => "final_amount_final"
								         }, as: :currency, label: "Total Amount: " %>
							</div>
					 	
				</div>
			</div>


		    	<br>

			    <div id="question_check">
			      <label class="form-check-label"> Do you wish to include a test question?
			          <button type="button" class="btn btn-secondary btn-sm">Yes</button>
			      </label>
			    </div>
		    
			    <div id="question_uncheck">
			      <label class="form-check-label"> Do you wish to include a test question?
			          <button type="button" class="btn btn-secondary btn-sm">No</button>
			      </label>
			    </div>

			    <div id="test_q">
			        <%= f.input :test_question, label: "Test Question: " %>
			        <%= f.input :test_answer, label: "Test Answer: " %>
			    </div>

		

    	<br>
    
    	<br>

	    <%= f.input :address, label: "Address: " %>
	    <%= f.input :address_zip, label: "Zip Code: " %>
	    <%= f.input :address_state, label: "State: " %>
	    <%= f.input :phone_number, label: "Phone Number: " %>
	    
	    <br>
	    
	    <div class="id_select">
	    	<%= f.input :id_type, collection: [['US Drivers License', '1'], ['Government ID', '2'], ['Passport', '3']] %>
	    </div>
	    
	    <div class='id_type' value='1' name='license'>
		      <%= f.input :lic_number, label: "License Number: " %>
		      <%= f.input :id_dob, label: "Date of Birth: "  %>
		      <%= f.input :lic_state, label: "State: "  %>
	    </div>

	    <div class='id_type' value='2' name='government'>
		   	<%= f.input :gov_number, label: "Gov. ID Number: "  %>
		    <%= f.input :id_dob, label: "Date of Birth: "  %>
		    <%= f.input :gov_nation, collection: @countries, input_html: { multiple: false}, label: "Country: "  %>
	    </div>


	    <div class='id_type' value='3' name='passport'>
		    <%= f.input :pass_number, label: "Passport Number: " %>
		    <%= f.input :id_dob, label: "Date of Birth: "  %>
		    <%= f.input :pass_nation, collection: @countries, input_html: { multiple: false}, label: "Country: "  %>
	    </div>

	    <br>

	    <div id="reciever_name_check">
	    	<label class="form-check-label"> Enter Materal and Paternal Names?
	        	<button type="button" class="btn btn-secondary btn-sm">Yes</button>
	    	</label>
	    </div>
	    
	    <div id="reciever_name_uncheck">
	    	<label class="form-check-label"> Enter Normal Last Name?
	        	<button type="button" class="btn btn-secondary btn-sm">Yes</button>
	    	</label>
	    </div>

	    	<%= f.input :reciever_f_name,  label: "First Name: " %>
	    	<%= f.input :reciever_m_name, label: "Middle Name: "  %>

	    <div id="reciever_name_reg" > 
	    	<%= f.input :reciever_l_name, label: "Last Name: "  %>
	    </div>
	    
	    <div id="reciever_name_alt">
	    	<%= f.input :reciever_pat_name, label: "Paternal Last Name: " %>
	    	<%= f.input :reciever_mat_name, label: "Maternal Last Name: "  %>
	    </div>
		
		<br>

    	<%= f.submit 'Submit Transaction' %>

  <% end %>

app/views/senders/edit.html.erb
<h1>Editing Sender</h1>

<%= render 'form', sender: @sender %>

<%= link_to 'Show', @sender %> |
<%= link_to 'Back', senders_path %>

app/views/senders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Senders</h1>

<table>
  <thead>
    <tr>
      <th>Customer Number</th>
      <th>MTCN</th>
      <th>First Name</th>
      <th>Middle Name</th>
      <th>Last Name</th>
      <th>Paternal Last Name</th>
      <th>Maternal Last Name</th>
      <th>Phone Number</th>
      <th>Email</th>
      <th>Address</th>
      <th>Zip Code</th>
      <th>State</th>
      <th>ID Type</th>
      <th>License Number</th>
      <th>Passport Number</th>
      <th>Government Id Number</th>
      <th>Date of Birth</th>
      <th>License State</th>
      <th>Passport Country</th>
      <th>Country Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @senders.each do |sender| %>
      <tr>
        <td><%= sender.customer_number %></td>
        <td><%= sender.mtcn %></td>
        <td><%= sender.f_name %></td>
        <td><%= sender.m_name %></td>
        <td><%= sender.l_name %></td>
        <td><%= sender.pat_name %></td>
        <td><%= sender.mat_name %></td>
        <td><%= sender.phone_number %></td>
        <td><%= sender.email %></td>
        <td><%= sender.address %></td>
        <td><%= sender.address_zip %></td>
        <td><%= sender.address_state %></td>
        <td><%= sender.id_type %></td>
        <td><%= sender.lic_number %></td>
        <td><%= sender.pass_number %></td>
        <td><%= sender.gov_number %></td>
        <td><%= sender.id_dob %></td>
        <td><%= sender.lic_state %></td>
        <td><%= sender.pass_nation %></td>
        <td><%= sender.gov_nation %></td>
        <td><%= link_to 'Show', sender %></td>
        <td><%= link_to 'Edit', edit_sender_path(sender) %></td>
        <td><%= link_to 'Destroy', sender, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sender', new_sender_path %>

app/views/senders/new.html.erb
<h1>New Sender</h1>

<div class="container">
	<%= render 'form', sender: @sender %>
</div>

<%= link_to 'Back', senders_path %>

app/views/senders/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Customer Number</th>
      <th>Create Account</th>
      <th>MTCN</th>
      <th>Converted Payout Amount</th>
      <th>Send Amount</th>
      <th>First Name</th>
      <th>Middle Name</th>
      <th>Last Name</th>
      <th>Paternal Last Name</th>
      <th>Maternal Last Name</th>
      <th>Phone Number</th>
      <th>Email</th>
      <th>Address</th>
      <th>Zip Code</th>
      <th>State</th>
      <th>ID Type</th>
      <th>License Number</th>
      <th>Passport Number</th>
      <th>Government Id Number</th>
      <th>Date of Birth</th>
      <th>License State</th>
      <th>Passport Country</th>
      <th>Country Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @sender.customer_number %></td>
        <td><%= @sender.create_account %></td>
        <td><%= @sender.mtcn %></td>
        <td><%= @sender.conversion_amount %></td>
        <td><%= @sender.send_amount %></td>
        <td><%= @sender.f_name %></td>
        <td><%= @sender.m_name %></td>
        <td><%= @sender.l_name %></td>
        <td><%= @sender.pat_name %></td>
        <td><%= @sender.mat_name %></td>
        <td><%= @sender.phone_number %></td>
        <td><%= @sender.email %></td>
        <td><%= @sender.address %></td>
        <td><%= @sender.address_zip %></td>
        <td><%= @sender.address_state %></td>
        <td><%= @sender.id_type %></td>
        <td><%= @sender.lic_number %></td>
        <td><%= @sender.reciever_f_name %></td>
        <td><%= @sender.reciever_m_name %></td>
        <td><%= @sender.reciever_l_name %></td>
        <td><%= @sender.reciever_pat_name %></td>
        <td><%= @sender.reciever_mat_name %></td>
        <td><%= @sender.pass_number %></td>
        <td><%= @sender.gov_number %></td>
        <td><%= @sender.id_dob %></td>
        <td><%= @sender.lic_state %></td>
        <td><%= @sender.pass_nation %></td>
        <td><%= @sender.gov_nation %></td>
        <td><%= link_to 'Show', @sender %></td>
        <td><%= link_to 'Edit', edit_sender_path(@sender) %></td>
        <td><%= link_to 'Destroy', @sender, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  </tbody>
</table>


<p>Transactions</p>

<table>
  <thead>
    <tr>
      <th>MTCN</th>
      <th>Payout Amount</th>
      <th>Sender First Name</th>
      <th>Sender Middle Name</th>
      <th>Sender Last Name</th>
      <th>Test Question</th>
      <th>Test Answer</th>     
      <th>Expected First Name</th>
      <th>Expected Middle Name</th>
      <th>Expected Last Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trans.each do |trans| %>
      <tr>
        <td><%= trans.mtcn %></td>
        <td><%= trans.payout_amount %></td>
        <td><%= trans.sender_f_name %></td>
        <td><%= trans.sender_m_name %></td>
        <td><%= trans.sender_l_name %></td>
        <td><%= trans.test_question %></td>
        <td><%= trans.test_quest_answer %></td>
        <td><%= trans.expected_f_name %></td>
        <td><%= trans.expected_m_name %></td>
        <td><%= trans.expected_l_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Edit', edit_sender_path(@sender) %> |
<%= link_to 'Back', senders_path %>